version: "1"

services:
  postgres1:
    container_name: "postgres1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    image: postgres:13
    volumes:
      - ./data/postgres1:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./createview.sql:/docker-entrypoint-initdb.d/createview.sql
  
  postgres2:
    container_name: "postgres2"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    image: postgres:13
    volumes:
      - ./data/postgres2:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./createview.sql:/docker-entrypoint-initdb.d/createview.sql
    